FROM python:3.11

ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY booky/requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/
WORKDIR /app/booky

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]