FROM python:3.11

ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY reco/requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/
WORKDIR /app/reco

EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0"]