# Generated by Django 4.2.15 on 2024-08-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_author_book_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
    ]
