# Generated by Django 4.2.15 on 2024-08-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_author_id_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
